-- ─────────────────────────────────────────────────────────────────────────────
-- Super admin comp-access codes
--
-- Extends ppv_invites with an `is_comp` flag so super_admin can generate
-- unlimited complimentary access codes for a given game. Regular invites
-- (generated by players / paid_fans) remain rate-limited to 1 per generator
-- per game; comp codes have no such limit.
--
-- The existing redemption flow (handleInviteRedeem + can_user_view_stream)
-- continues to work unchanged because it already reads from ppv_invites
-- without caring about the generator type.
--
-- Rules inherited from PPV on redemption:
--   - IP-locked on first use                     (handleInviteRedeem)
--   - Non-transferable across users              (handleInviteRedeem)
--   - Creates a stream_entitlement               (handleInviteRedeem)
--   - Playback session is 6-hour-capped          (createOrRefreshPlaybackSession)
--   - One-device enforcement                     (createOrRefreshPlaybackSession)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1) Add the is_comp flag + optional note for ops tracking.
ALTER TABLE public.ppv_invites
  ADD COLUMN IF NOT EXISTS is_comp BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.ppv_invites
  ADD COLUMN IF NOT EXISTS note TEXT;

-- 2) Relax the 1-invite-per-generator-per-game uniqueness to only apply to
--    NON-comp rows. Super admin comp codes are unlimited.
ALTER TABLE public.ppv_invites
  DROP CONSTRAINT IF EXISTS ppv_invites_generated_by_game_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS ppv_invites_generated_by_game_id_regular_uq
  ON public.ppv_invites (generated_by, game_id)
  WHERE is_comp = FALSE;

-- 3) Helpful index for listing comp codes in the admin UI.
CREATE INDEX IF NOT EXISTS idx_ppv_invites_comp_generator
  ON public.ppv_invites (generated_by, created_at DESC)
  WHERE is_comp = TRUE;

COMMENT ON COLUMN public.ppv_invites.is_comp IS
  'TRUE for super_admin-issued comp access codes (unlimited per game). '
  'FALSE for regular player/paid_fan invites (1 per generator per game).';
